## Introduction

The data provided is from a delivery app which we intend to analyze to identify patterns, trends, and correlations that can help retailers optimize their marketing, pricing, and product strategies to increase sales and revenue.

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder, StandardScaler

import warnings
warnings.filterwarnings("ignore")

In [4]:
data = pd.read_csv("Supermart Grocery Sales - Retail Analytics Dataset.csv")
data.head()

,Order ID,Customer Name,Category,Sub Category,City,Order Date,Region,Sales,Discount,Profit,State
0,OD1,Harish,Oil & Masala,Masalas,Vellore,11-08-2017,North,1254,0.12,401.28,Tamil Nadu
1,OD2,Sudha,Beverages,Health Drinks,Krishnagiri,11-08-2017,South,749,0.18,149.80,Tamil Nadu
2,OD3,Hussain,Food Grains,Atta & Flour,Perambalur,06-12-2017,West,2360,0.21,165.20,Tamil Nadu
3,OD4,Jackson,Fruits & Veggies,Fresh Vegetables,Dharmapuri,10-11-2016,South,896,0.25,89.60,Tamil Nadu
4,OD5,Ridhesh,Food Grains,Organic Staples,Ooty,10-11-2016,South,2355,0.26,918.45,Tamil Nadu

### Data Wrangling

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   object
 1   Customer Name  9994 non-null   object
 2   Category       9994 non-null   object
 3   Sub Category   9994 non-null   object
 4   City           9994 non-null   object
 5   Order Date     9994 non-null   object
 6   Region         9994 non-null   object
 7   Sales          9994 non-null   int64
 8   Discount       9994 non-null   float64
 9   Profit         9994 non-null   float64
 10  State          9994 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 859.0+ KB

#### Data Discovery

In [6]:
data.isnull().sum()

Order ID         0
Customer Name    0
Category         0
Sub Category     0
City             0
Order Date       0
Region           0
Sales            0
Discount         0
Profit           0
State            0
dtype: int64

In [ ]:
#Select the categorical columns to encode
cat_cols = ['State', 'Region','Category', 'Sub Category', 'City',]

# categorical_columns = data.select_dtypes(include=['object']).columns.tolist()
# categorical_columns

['Order ID',
 'Customer Name',
 'Category',
 'Sub Category',
 'City',
 'Order Date',
 'Region',
 'State']

In [12]:

# def get_feature_names(encoder, cat_cols):
#   return [f"{col}{category}" for i, col in enumerate(cat_cols) for category in encoder.categories[i]]

# Encode categorical columns with one-hot encoding
encoder = OneHotEncoder(sparse_output=False)
cat_cols_encoded = encoder.fit_transform(data[cat_cols])

# Create DataFrame with encoded categorical columns

one_hot_df = pd.DataFrame(cat_cols_encoded, columns=encoder.get_feature_names_out(cat_cols))

df_encoded = pd.concat([data, one_hot_df], axis=1)

df_encoded = df_encoded.drop(cat_cols,  axis=1)
df_encoded.head()
# print(f"Encoded Sales data : \n{df_encoded}")

,Order ID,Customer Name,Category,Sub Category,City,Order Date,Sales,Discount,Profit,State_Tamil Nadu,Region_Central,Region_East,Region_North,Region_South,Region_West
0,OD1,Harish,Oil & Masala,Masalas,Vellore,11-08-2017,1254,0.12,401.28,1.0,0.0,0.0,1.0,0.0,0.0
1,OD2,Sudha,Beverages,Health Drinks,Krishnagiri,11-08-2017,749,0.18,149.80,1.0,0.0,0.0,0.0,1.0,0.0
2,OD3,Hussain,Food Grains,Atta & Flour,Perambalur,06-12-2017,2360,0.21,165.20,1.0,0.0,0.0,0.0,0.0,1.0
3,OD4,Jackson,Fruits & Veggies,Fresh Vegetables,Dharmapuri,10-11-2016,896,0.25,89.60,1.0,0.0,0.0,0.0,1.0,0.0
4,OD5,Ridhesh,Food Grains,Organic Staples,Ooty,10-11-2016,2355,0.26,918.45,1.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
# Define numerical columns
num_cols = data.select_dtypes(include='number').columns.tolist()

# Concatenate numerical and encoded categorical columns
X = pd.concat([data[num_cols], cat_cols_df], axis=1)

#Encode the categorical columns and concatenate with the numerical columns
X = pd.concat([data.select_dtypes(include='number'),
pd.DataFrame(encoder.transform(data[cat_cols]),
columns=encoder.get_feature_names_out(cat_cols))],
axis=1)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

#Define transformers
num_transformer = StandardScaler()
cat_transformer = OneHotEncoder()

#Define column transformer
preprocessor = ColumnTransformer(
transformers=[
('num', num_transformer, num_cols),
('cat', cat_transformer, cat_cols)
])

#Fit and transform data
X = preprocessor.fit_transform(data)

In [ ]:
# Create Predictor and response variables

X = data[["Sales", "Discount"]]
y = data["Profit"]